In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
my = pd.read_csv('maoyanfilms_clean.csv')

In [3]:
my = my.drop(['Unnamed: 0','films_id','films_name','films_comment_num','films_director','films_actor','films_introduction','films_comment'],axis=1)

In [4]:
my

films_type films_area films_duration film_first_time  films_score  \
0            喜剧 , 爱情        中国大陆          122分钟      2010-12-22          7.4   
1                 爱情        中国香港          117分钟      2009-01-26          6.1   
2            爱情 , 剧情   中国台湾,中国大陆          128分钟      2012-02-14          7.8   
3                 爱情   中国大陆,中国香港          112分钟      2012-02-09          7.1   
4       爱情 , 音乐 , 奇幻   中国香港,中国台湾          101分钟      2007-07-31          8.5   
...               ...        ...            ...             ...          ...   
15425             NaN       中国香港           13分钟         2015-12          NaN   
15426        剧情 , 短片        中国大陆           20分钟      2019-06-25          NaN   
15427       纪录片 , 短片        中国大陆            4分钟            2016          NaN   
15428             喜剧        中国香港          125分钟      2012-10-11          NaN   
15429            纪录片        中国台湾           61分钟      2018-10-25          NaN   

       films_box_office  
0               47200.0  
1               11299.0  
2               13700.0  
3                2137.0  
4                  33.0  
...                 ...  
15425               NaN  
15426               NaN  
15427               NaN  
15428               NaN  
15429               NaN  

[15430 rows x 6 columns]

In [5]:
my.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15430 entries, 0 to 15429
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   films_type        13584 non-null  object 
 1   films_area        15430 non-null  object 
 2   films_duration    15430 non-null  object 
 3   film_first_time   15427 non-null  object 
 4   films_score       2520 non-null   float64
 5   films_box_office  1501 non-null   float64
dtypes: float64(2), object(4)
memory usage: 723.4+ KB


### 删掉电影类型为空的行

In [6]:
my=my.dropna(subset=['films_type'])

In [7]:
my.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13584 entries, 0 to 15429
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   films_type        13584 non-null  object 
 1   films_area        13584 non-null  object 
 2   films_duration    13584 non-null  object 
 3   film_first_time   13581 non-null  object 
 4   films_score       2510 non-null   float64
 5   films_box_office  1501 non-null   float64
dtypes: float64(2), object(4)
memory usage: 742.9+ KB


In [8]:
my

films_type films_area films_duration film_first_time  films_score  \
0            喜剧 , 爱情        中国大陆          122分钟      2010-12-22          7.4   
1                 爱情        中国香港          117分钟      2009-01-26          6.1   
2            爱情 , 剧情   中国台湾,中国大陆          128分钟      2012-02-14          7.8   
3                 爱情   中国大陆,中国香港          112分钟      2012-02-09          7.1   
4       爱情 , 音乐 , 奇幻   中国香港,中国台湾          101分钟      2007-07-31          8.5   
...               ...        ...            ...             ...          ...   
15423             短片        中国香港           30分钟      2018-05-17          NaN   
15426        剧情 , 短片        中国大陆           20分钟      2019-06-25          NaN   
15427       纪录片 , 短片        中国大陆            4分钟            2016          NaN   
15428             喜剧        中国香港          125分钟      2012-10-11          NaN   
15429            纪录片        中国台湾           61分钟      2018-10-25          NaN   

       films_box_office  
0               47200.0  
1               11299.0  
2               13700.0  
3                2137.0  
4                  33.0  
...                 ...  
15423               NaN  
15426               NaN  
15427               NaN  
15428               NaN  
15429               NaN  

[13584 rows x 6 columns]

### 其他特征的处理

In [9]:
my['films_type'] = my['films_type'].apply(lambda x: x.split(',')[0])

In [10]:
def handle_area(x):
    area = ['中国大陆','中国香港','中国台湾'] 
    area_list = x.split(',')
    for a in area_list:
        if a in area:
            return a
        else:
            continue
my['films_area'] = my['films_area'].apply(handle_area)

In [11]:
my.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13584 entries, 0 to 15429
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   films_type        13584 non-null  object 
 1   films_area        13544 non-null  object 
 2   films_duration    13584 non-null  object 
 3   film_first_time   13581 non-null  object 
 4   films_score       2510 non-null   float64
 5   films_box_office  1501 non-null   float64
dtypes: float64(2), object(4)
memory usage: 742.9+ KB


In [12]:
my=my.dropna(subset=['films_area'])

In [13]:
my.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13544 entries, 0 to 15429
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   films_type        13544 non-null  object 
 1   films_area        13544 non-null  object 
 2   films_duration    13544 non-null  object 
 3   film_first_time   13541 non-null  object 
 4   films_score       2508 non-null   float64
 5   films_box_office  1500 non-null   float64
dtypes: float64(2), object(4)
memory usage: 740.7+ KB


In [14]:
my=my.dropna(subset=['film_first_time'])

In [15]:
my.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13541 entries, 0 to 15429
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   films_type        13541 non-null  object 
 1   films_area        13541 non-null  object 
 2   films_duration    13541 non-null  object 
 3   film_first_time   13541 non-null  object 
 4   films_score       2506 non-null   float64
 5   films_box_office  1500 non-null   float64
dtypes: float64(2), object(4)
memory usage: 740.5+ KB


In [16]:
my['films_duration'] = my['films_duration'].apply(lambda x: int(x[:-2]))

In [17]:
my['film_first_time'] = my['film_first_time'].apply(lambda x: int(x[0:4]))

In [18]:
my['films_score'] = my['films_score'].apply(lambda x: float(x))

In [19]:
my['films_box_office'] = my['films_box_office'].apply(lambda x: float(x))

In [20]:
my.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13541 entries, 0 to 15429
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   films_type        13541 non-null  object 
 1   films_area        13541 non-null  object 
 2   films_duration    13541 non-null  int64  
 3   film_first_time   13541 non-null  int64  
 4   films_score       2506 non-null   float64
 5   films_box_office  1500 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 740.5+ KB


In [21]:
my.head(6)

films_type films_area  films_duration  film_first_time  films_score  \
0        喜剧        中国大陆             122             2010          7.4   
1        爱情        中国香港             117             2009          6.1   
2        爱情        中国台湾             128             2012          7.8   
3        爱情        中国大陆             112             2012          7.1   
4        爱情        中国香港             101             2007          8.5   
5        喜剧        中国大陆             110             2008          5.1   

   films_box_office  
0           47200.0  
1           11299.0  
2           13700.0  
3            2137.0  
4              33.0  
5            3500.0

# 特征工程

### 提取特征 独热编码

In [26]:
f_type = pd.get_dummies(my['films_type']) 

In [27]:
f_type.head(3)

Sci-Fi    亲情    传记    儿童    公益    公益性    公路喜剧    冒险    军旅   ...   警匪   \
0   0         0     0     0     0     0      0       0     0     0  ...     0   
1   0         0     0     0     0     0      0       0     0     0  ...     0   
2   0         0     0     0     0     0      0       0     0     0  ...     0   

    记录片    运动    都市    青春    青春 励志 爱情    青春励志    音乐    魔幻    黑色电影   
0      0     0     0     0           0       0     0     0       0  
1      0     0     0     0           0       0     0     0       0  
2      0     0     0     0           0       0     0     0       0  

[3 rows x 79 columns]

In [28]:
f_area = pd.get_dummies(my['films_area'])

In [29]:
f_area.head(3)

中国台湾  中国大陆  中国香港
0     0     1     0
1     0     0     1
2     1     0     0

In [30]:
my = my.join(f_type)
my = my.join(f_area)

In [31]:
my.head(5)

films_type films_area  films_duration  film_first_time  films_score  \
0        喜剧        中国大陆             122             2010          7.4   
1        爱情        中国香港             117             2009          6.1   
2        爱情        中国台湾             128             2012          7.8   
3        爱情        中国大陆             112             2012          7.1   
4        爱情        中国香港             101             2007          8.5   

   films_box_office       Sci-Fi    亲情    传记   ...   都市    青春    青春 励志 爱情   \
0           47200.0   0         0     0     0  ...     0     0           0   
1           11299.0   0         0     0     0  ...     0     0           0   
2           13700.0   0         0     0     0  ...     0     0           0   
3            2137.0   0         0     0     0  ...     0     0           0   
4              33.0   0         0     0     0  ...     0     0           0   

    青春励志    音乐    魔幻    黑色电影   中国台湾  中国大陆  中国香港  
0       0     0     0       0     0     1     0  
1       0     0     0       0     0     0     1  
2       0     0     0       0     1     0     0  
3       0     0     0       0     0     1     0  
4       0     0     0       0     0     0     1  

[5 rows x 88 columns]

In [32]:
my = my.drop(['films_type','films_area'],axis=1)

### 缺失值填充 中位数

In [33]:
# 中位数
f_score_median = my['films_score'].median()
f_office_median = my['films_box_office'].median()
my['films_score'] =my['films_score'].fillna(f_score_median)
my['films_box_office'] = my['films_box_office'].fillna(f_office_median)

### 数据集选择

In [34]:
data = my.loc[:,my.columns != 'films_box_office'].values
label = my.loc[:,my.columns == 'films_box_office'].values

In [35]:
np.set_printoptions(suppress=True)
data

array([[ 122. , 2010. ,    7.4, ...,    0. ,    1. ,    0. ],
       [ 117. , 2009. ,    6.1, ...,    0. ,    0. ,    1. ],
       [ 128. , 2012. ,    7.8, ...,    1. ,    0. ,    0. ],
       ...,
       [   4. , 2016. ,    6.9, ...,    0. ,    1. ,    0. ],
       [ 125. , 2012. ,    6.9, ...,    0. ,    0. ,    1. ],
       [  61. , 2018. ,    6.9, ...,    1. ,    0. ,    0. ]])

In [36]:
label = label.flatten()
label

array([47200. , 11299. , 13700. , ...,   315.5,   315.5,   315.5])

## 特征选择

### 卡方检验

In [37]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

#递归特征消除法，返回特征选择后的数据
#参数estimator为基模型
#参数n_features_to_select为选择的特征个数
featureArr = RFE(estimator=LogisticRegression(), n_features_to_select=12).fit_transform(data, label.astype('int'))
print(featureArr)

[[7.4 0.  0.  ... 0.  1.  0. ]
 [6.1 0.  0.  ... 0.  0.  1. ]
 [7.8 0.  0.  ... 1.  0.  0. ]
 ...
 [6.9 0.  0.  ... 0.  1.  0. ]
 [6.9 0.  0.  ... 0.  0.  1. ]
 [6.9 0.  0.  ... 1.  0.  0. ]]


### 相关系数法

In [ ]:
from sklearn.feature_selection import SelectKBest
from scipy.stats import pearsonr

#选择K个最好的特征，返回选择特征后的数据
#第一个参数为计算评估特征是否好的函数，该函数输入特征矩阵和目标向量，输出二元组（评分，P值）的数组，数组第i项为第i个特征的评分和P值。在此定义为计算相关系数
#参数k为选择的特征个数
SelectKBest(lambda X, Y: array(map(lambda x:pearsonr(x, Y), X.T)).T, k=2).fit_transform(iris.data, iris.target)

### 递归特征消除法

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

#递归特征消除法，返回特征选择后的数据
#参数estimator为基模型
#参数n_features_to_select为选择的特征个数
RFE(estimator=LogisticRegression(), n_features_to_select=12).fit_transform(data,label.astype('int'))

## 降维

### 主成分分析法 PCA

In [43]:
from sklearn.decomposition import PCA
#主成分分析法，返回降维后的数据
#参数n_components为主成分数目
data = PCA(n_components=6).fit_transform(featureArr)
print(data)

[[-0.54859975 -0.16226606  0.47512136  0.41921462 -0.45826603  0.70990641]
 [ 1.07734475 -0.54195081 -0.12160843  0.76684985  0.15229722 -0.36925951]
 [-0.59681374 -1.13547827 -0.51038282 -0.13278182 -0.68448688 -0.21925912]
 ...
 [-0.1574833  -0.31054972  0.67203101 -0.36864163  0.53248026  0.05577262]
 [ 0.36854882 -0.77801883 -0.19601553  1.04879942 -0.06069364  0.64721473]
 [ 0.20786794 -1.19477193 -0.17500101 -0.80183348  0.1176929   0.11887261]]


### 线性判别分析法 LDA

In [ ]:
from sklearn.lda import LDA 
#线性判别分析法，返回降维后的数据
#参数n_components为降维后的维数
data = LDA(n_components=6).fit_transform(data,label)

### 机器学习

In [44]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.ensemble import AdaBoostRegressor # AdaBoost回归器

In [45]:
rf = RandomForestRegressor()
parameters = {"randomforestregressor__n_estimators": range(20,25)}
pipeline = Pipeline([('randomforestregressor', rf)])

In [46]:
clf = GridSearchCV(estimator=pipeline, param_grid=parameters)

In [47]:
clf.fit(featureArr,label)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split=None,
                                                              min_samples_leaf=1,
                                                              min_samples_split=2,
                                                              min_weight_fraction_leaf=0.0,

In [48]:
print("最优分数： %.4lf" %clf.best_score_)
print("最优参数：", clf.best_params_)

最优分数： 0.1156
最优参数： {'randomforestregressor__n_estimators': 20}


In [49]:
reg = AdaBoostRegressor()
parameters = {"adaboostregressor__n_estimators": range(10,30)}
pipeline = Pipeline([('adaboostregressor', reg)])

In [50]:
clf_ada = GridSearchCV(estimator=pipeline, param_grid=parameters)

In [51]:
clf_ada.fit(featureArr,label)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('adaboostregressor',
                                        AdaBoostRegressor(base_estimator=None,
                                                          learning_rate=1.0,
                                                          loss='linear',
                                                          n_estimators=50,
                                                          random_state=None))],
                                verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'adaboostregressor__n_estimators': range(10, 30)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [52]:
print("最优分数： %.4lf" %clf_ada.best_score_)
print("最优参数：", clf_ada.best_params_)

最优分数： -0.5895
最优参数： {'adaboostregressor__n_estimators': 15}


In [53]:
# 选用了4种回归模型，最小二乘法 、 岭回归、索套、随机森林
from sklearn import model_selection
from sklearn.ensemble import RandomForestRegressor as RFR # 随机森林
from sklearn.linear_model import LinearRegression as LR # 最小二乘法
from sklearn.linear_model import Ridge as R # 岭回归
from sklearn.linear_model import Lasso as L # 索套
import warnings
warnings.filterwarnings("ignore")

In [55]:
def predict_score(data,label,model):
    i = np.random.permutation(len(data))
    x_train = data[i[:-3584]]
    y_train = label[i[:-3584]]
    x_test = data[i[-3584:]]
    y_test = label[i[-3584:]]
    Model = model()
    Model.fit(x_train,y_train)
    score = Model.score(x_test,y_test)
    return score

In [56]:
modellist = [RFR,LR,R,L]
for m in modellist:
    model = m
    score = predict_score(featureArr,label,model)
    print(str(model)+'回归模型的准确率为'+str(score))

<class 'sklearn.ensemble.forest.RandomForestRegressor'>回归模型的准确率为0.12966346592077282
<class 'sklearn.linear_model.base.LinearRegression'>回归模型的准确率为-0.004354904805465409
<class 'sklearn.linear_model.ridge.Ridge'>回归模型的准确率为0.05227504102204439
<class 'sklearn.linear_model.coordinate_descent.Lasso'>回归模型的准确率为0.03746306517716158
